<!DOCTYPE html>
<head>
<h1>
    THIS IS THE LICESNCING AND MOTORBIKES PAGE
</h1>
</head>
<body>
THIS WILL PROVIDE INFORMATION ON THE MAKE
 AND THE VALIDIDTY OF THE MOTOR BIKE
</body>

</html>